<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body><!DOCTYPE html>
<html>

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>AvaIn</title>
        <link rel="stylesheet" type="text/css" href="css/site.css">
        <link rel="stylesheet" type="text/css" href="css/carousel.css">

        <!-- This demo works with jquery library -->
        <script type="text/javascript" src="js/jquery-1.11.3.min.js"></script>
        <script type="text/javascript" src="js/jssor.slider.mini.js"></script>
        <script type="text/javascript" src="js/carousel.js"></script>
    </head>

    <body>	
        
        <?php
        // put your code here
        ?>
        <div class="page-wrap">
            <nav class="nav">
                <ul style="display:inline-block;">
                    <li>
                        <a href="Index.php">Inicio</a><li>
                        <a href="Login.html">Logar</a>
                        <a href="ListaAtividades.html">Atividades</a>
                        <a href="ListaAlunos.html">Alunos</a>
                        <a href="Cadastrar.html">Cadastrar</a>
                        <a href="Cadastrar.html">Cadastrar</a>
                        <a href="Cadastrar.html">Gerar</a></li>
                </ul>
                <br />
            </nav>
            <div>
                <br />
                <table style="width:100%">
                    <tbody>
                        <tr>
                            <td style="width:70%">
                                <input id="inputPesquisar" type="text">
                            </td>
                            <td>
                                <input style="height:20px;" class="button-small-full" value="Pesquisar" type="button" />
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>		
            <br />

            <div style="text-align:center;">
                <h1 id="Rotina"></h1>
            </div>
            <div style="background:#FDF3E7;padding:10px;border-radius:10px;">
                <div class="nav nav-right"></div>
<!--                <table style="width:100%">
					<tr>
						<td class="link" onclick="window.location.href = '#Promocao';" style="width:100%;display:block;">
							 #region Jssor Slider Begin 
							 Generated by Jssor Slider Maker. 
							 This demo works with jquery library 
							 #carousel 
							<div class="carousel">
								<div class="nav nav-left"></div>
									<div class="overflow">
										<div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 809px; height: 150px; overflow: hidden; visibility: hidden;">
											 Loading Screen 
											<div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
												<div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
												<div style="position:absolute;display:block;background:url('img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
											</div>
											<div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 809px; height: 150px; overflow: hidden;">
												<div style="display: none;">
													<a href="Blocos.html"><img data-u="image" src="imagens/Blocos.jpg" /></a>
												</div>
												<div style="display: none;">
													<a href="brinquedos.html"><img data-u="image" src="imagens/brinquedos.jpg" /></a>
												</div>
												<div style="display: none;">
													<a href="chegada.html"><img data-u="image" src="imagens/chegada.jpg" /></a>
												</div>
												<div style="display: none;">
													<a href="HoraConto1.html"><img data-u="image" src="imagens/HoraConto1.jpg" /></a>
												</div>
												<div style="display: none;">
													<a href="lanche.html"><img data-u="image" src="imagens/lanche.jpg" /></a>
												</div>
												<div style="display: none;">
													<a href="leitura.html"><img data-u="image" src="imagens/leitura.jpg" /></a>
												</div><div style="display: none;">
													<a href="pracinha.html"><img data-u="image" src="imagens/pracinha.jpg" /></a>
												</div><div style="display: none;">
													<a href="trabalhosManuais.html"><img data-u="image" src="imagens/trabalhosManuais.jpg" /></a>
												</div>
											</div>
											 Bullet Navigator 
												<div data-u="navigator" class="jssorb03" style="bottom:10px;right:10px;">
												 bullet navigator item prototype 
												<div data-u="prototype" style="width:21px;height:21px;">
												<div data-u="numbertemplate"></div>
												</div>
												</div>
											 Arrow Navigator 
											<span data-u="arrowleft" class="jssora03l" style="top:0px;left:8px;width:55px;height:55px;" data-autocenter="2"></span>
											<span data-u="arrowright" class="jssora03r" style="top:0px;right:8px;width:55px;height:55px;" data-autocenter="2"></span>
										</div>
									 #carousel 
									</div>
							</div>
						</td>
					</tr>
				</table>-->
				<div class="nav nav-right"></div>
			</div>				
			<br />

            <div style="text-align:center;">
                <h1 id="Rotina">Rotina</h1>
                <h2 id="Rotina">Manhã:</h2>
            </div>
            <div style="background:#FDF3E7;padding:10px;border-radius:10px;">
                <table style="width:100%">
                    <tr>

                        <td class="link" onclick="window.location.href = '#Escova';" style="width:100%;display:block;">
                            <div class="produtoItem">
                                <a>Chegada</a>
                                <img src="imagens/chegada.jpg" alt="Chegada" />
                                <p>7:30 às 9:00 e 13:00 às 13:30</p>
                                <p> Horário de Entrada</p>



                            </div>
                        </td>
                        <td class="link" onclick="window.location.href = '#Escova';" style="width:100%;display:block;">
                            <div class="produtoItem">
                                <a>Brinquedos</a>
                                <img src="imagens/brinquedos.jpg" alt="Brinquedos" />
                                <p>9:30 às 10:00</p>
                                <p> Brinquedo Livre</p>
                            </div>
                        </td>
                    </tr>
                </table>				
            </div>

            <div style="text-align:center;">
                <h2 id="Pente">Tarde:</h2>
            </div>
            <div style="background:#FDF3E7;padding:10px;border-radius:10px;">
                <table style="width:100%">
                    <tr>
                        <td class="link" onclick="window.location.href = '#Pente';" style="width:100%;display:block;">
                            <div class="produtoItem">
                                <a>Brinquedos</a>
                                <img src="imagens/brinquedos.jpg" alt="Brinquedos" />
                                <p>9:30 às 10:00</p>
                                <p> Brinquedo Livre</p>
                            </div>
                        </td>
                        <td class="link" onclick="window.location.href = '#Pente';" style="width:100%;display:block;">
                            <div class="produtoItem">
                                <p></p>
                                 <a>Brinquedos</a>
                                <img src="imagens/brinquedos.jpg" alt="Brinquedos" />
                                <p>9:30 às 10:00</p>
                                <p> Brinquedo Livre</p>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>

        <footer class="site-footer">
            Site: SIS API
            <br />
            <a class="link" href="FaleConosco.html">Fale Conosco</a>
        </footer>
   
    </body>
</html>
